### ISSUE TITLE
instability use

### ISSUE THREAD

**Issue by Startigen** [abaskind/hedrot#2]
Hello,
I try to use Hedrot receiver , but some position come back alone. I turn the headphone, I stop, and slowly (but not more) the position at the screen come back as before ... Have you an idea ?
I just want Yawl , but when I select only yawl , no change ...
I try with two PC under W7, the same think
Thank you
Regards

**Comment by abaskind** [comment]
Hi,

can you confirm that the magnetometer and the accelerometer are correctly calibrated?

best regards,

Alexis

**Comment by Startigen** [comment]
Fine, you're quickly …!

I made many calibrations , slowly, quickly , on my head, with the headphone in my hand … always the same thing.

And fot the Yawl only ?

Cheers

**Comment by abaskind** [comment]
This problem usually means that the magnetometer is bad calibrated, or that the magnetic environment is not suitable. Try to set the "Max Beta" parameter (in "receiver settings") to zero and let me know what happens.

The "yaw only" parameter has no influence on the calculation, it just forbids the other angles to be transmitted.

Best

Alexis

**Comment by Startigen** [comment]
Hi Alexis,

I put Max Beta to zero. At the first time : yes !!! but no, the position is not steady (stable …?) , very slowly the position go out …

Operation mode :

I launch the program , Headtracker on, the headphones on the table, screen calibrating very short, in the window position rotation card, then, nothing move, all is ok

I put  Max beta to zero, very slowly all parameters increase (Y P R) …

Cheers

Henry

**Comment by Startigen** [comment]
Hi Alexis,

An electronic friend is coming … he made a calibration … he made big and quick motion , very wide … It's very very very better. I just turn on the 3 axes , quiet … 

I'm sorry to disturb you, thank you very much for your time, and applauses for the project !

A last question … for sound, with my bino, what's good value for Max Beta ?

Cheers and thanks

Henry

**Comment by abaskind** [comment]
Hi Henry,

Good that you made it work. A good calibration is indeed crucial for the quality of the result. 

As I wrote before: the magnetometer may fail in some environments (which is always the case with such technologies). If this is the case, put Beta to zero. The problem of that, as you noticed, is drifting: for rapid mouvements, the zero may slowly deviate. The purpose of the beta parameter is to allow the zero to recalibrate in real-time according to the informations given by the magnetometer and the accelerometer, which works very well if the whole is well calibrated.

For your question: values of Beta lower than 10 are usually a good idea. If Beta is too high, the movement is less fluid.

All the best

Alexis

**Comment by WernerBleisteiner** [comment]
Hi Alexis, Henry,

thanks for these hints. That reminded me, that I have my hedrot project still unfinished, due to maybe similar issues (but I never got up to ask ;) ). So I will try now again.
But anyway, could any of you describe a bit more in detail how a calibration is supposed to be done? I also tried quite a few time before giving up. How small and slow - or big and quick do calibration motions have to be? Difficult to imagine if you never did that before. Thanks.

w

**Comment by abaskind** [comment]
Hi Werner,

sorry for my late answer. The calibration process is explained in the doc, let me summarize it:

. the accelerometer has to be calibrated normally once for ever. The principle is to scale to 1 the acceleration of gravity on all direction, only the acceleration of gravity, without any other acceleration. This means that it has to be calibrated very slowly, so that other kinds of acceleration can be neglected. If the calibration suceeds, the norm of the accelerometer data should be very close to 1 every time the sensor is still

. the magnetometer should be calibrated in order to scale to 1 the constant part of the magnetic field. In free field, the magnetic field mostly corresponds to the earth magnetic field, so basically a magnetometer becomes a compass. The problem is however that the magnetic field in a closed environment is very much different, because of the so-called "soft" and "hard" iron distortions. Any sources of magnetic field disturb the magnetometer, as well as ferromagnetic materials. This is the main reason the magnetometer is sometimes tricky to use, and should be used as far as possible from iron and/or magnetic sources. The calibration can be done very quickly but may have to be repeated often. If it succeeds, the norm of the vector should be 1 all the time. 

All the best

Alexis

**Comment by WernerBleisteiner** [comment]
Thanks Alexis.
I must have missed the detailed description, sorry.
I'll give it another try. 
Initially I had already data coming through. But although having run through a process that was declared "finished" - the next message was "not calibrated". So I presume probably the soldering might have damaged a component.
Anyway still hope to get it going, as I have some applications from our object-based audio pilot project to experience in dynamic binaural rendering :)

Best regards

w

twitter.com/3DAudioSurround

**Comment by abaskind** [comment]
Hi Werner,

that sounds indeed strange, but I doubt it's a soldering issue, it looks more like a communication problem. The best would be that you try it again and send me a more detailed report of the process: which sensor did you want to calibrate, which version of hedrot are you using, etc...

Best

Alexis
