### ISSUE TITLE
Calibrating Accelerometer not possible

### ISSUE THREAD

**Issue by halbius** [abaskind/hedrot#5]
Hi,

I'm trying desperately to calibrate the accelerometer. I tried it at different speeds. Sometimes it just breaks before clicking "Calibration done", sometimes it stops in between and it allways ends up saying "Calibration failed"
When choosing another calibration method, the receiver crashes.

Has anyone any idea?

Thanks a lot!

**Comment by abaskind** [comment]
Hi Halbius,

This project is officially not maintained any more. I'll try anyway to help you.

Crashes during calibration are astonishing and could be related to a physical serial communication problem, for instance because of a bad contact. Could you please tell me the following:

. which OS (windows or mac) and version?
. are you using the standalone or Max version of the receiver?
. could you provide a copy of the crashlog?
. have you double-checked all contacts, especially the contact between the USB cable and the USB socket?
. during the calibration, can you confirm me that all 3 axes (x, y, z) in the raw accelerometer data are varying?

All the best,

Alexis

**Comment by halbius** [comment]
Hi Alexis,

thanks for the fast response.

It's a pitty to hear that the project is down as I read somewhere (I think on the myBino site) that it is still alive, supported and in development. :(

Your questions: 

- OS: Win10 Pro, 64 Bit
- I use the standalone version
- Crashlog: I have to look, where I can find it.
- Contacts seem to be fine
- RAW-Accelerometer: Yes, all values are varying

Thanks a lot,

Christian

**Comment by abaskind** [comment]
Well, most probably the problem comes from the OS: the compilation has been done on Windows 7 and problems were already mentioned on the latest versions of Windows 10. Since it was the time we had to stop the developement, this could not be solved. 

I guess the problem is not that hard to solve for someone who's specialized in compilation on Windows, but this is not my case. Any help at this stage would be greatly appreciated by the windows 10 users.

To be sure that it comes from the soft and not from the hardware: could you try it once on a Mac?

Alexis

**Comment by halbius** [comment]
I'm afraid a Mac is not around.
Maybe I can get an old Win7 and give it a try.

But if there is someone out there who is able solve the Win10 problem, it would be great.
Or if someone knows an adequate alternative, it would work for me too...

Thanks, Christian

**Comment by halbius** [comment]
So I tried it on Win7 64Bit. hedrotReceiver doesn't start at all but crashes because of a Problem, aus Windows says...

In the meantime I tried a different headtracker and a pure data patch to translate the osc messages to mybino Format.
But the problem ist to connect to mybino. I tried it with /hedrot/<parameter> and of course the corresponding port, but it doesn't work.

Maybe you can give me a hint how the connection can be done?
I tried at x-audio directly, but no response till now. ☹️

Thanks a lot!

**Comment by abaskind** [comment]
Hi Halbius,

the osc messages to mybino should be straightforward. I have very limited knowledge about pure data, but in Max it works without any problem with the patch below:
![Screen Shot 2019-12-18 at 01 34 22](https://user-images.githubusercontent.com/23248437/71045790-aa758300-2136-11ea-862c-7a7eac3a0c20.png)

Alexis

**Comment by halbius** [comment]
Hm, very strange.

I did the same, no success. I tried it with max, it don't work. The OSC messages work fine, I tried it with other clients.
Actually when I open the hedrot receiver and change the values in the OSC-settings manually, it works fine and the MyBino-Head moves around...

**Comment by abaskind** [comment]
In between I tried the same with pure data (pd extended and vanilla, using sendOSC, as well as packOSC/udpsend): I also don't manage to send messages to mybino. Considering my almost non-existing knowledge of PD, I cannot guarantee that I set everything correctly (although I can send and receive OSC messages within PD), or if the OSC format used in mybino is not 100% compatible with PD. The mybino project being over as well, I guess it may be hard to have tips from the developers.

May I suggest a third solution, using Reaper? The idea is to use the vst version of mybino and instantiate it in audio tracks, then send the OSC messages not to mybino but to reaper itself, then map them in VST parameters. Look at the hedrot manual and/or the video tutorial of mybino for more details.

I'm sorry that I cannot help further for the unstability problems on windows, it's not my speciality at all (I'm a sound engineer, not a software engineer), and since the project is officially over, I don't have enough time to get familiar with it. It would be indeed very good is someone who know the stuff finds the right compilation parameters to make it stable on all versions of Windows 7 and 10. Another very good nice-to-have would be to compile a PD version of hedrot , it's technically possible and probably straightforward for someone who's familiar with compiling PD externals. 


Alexis

**Comment by halbius** [comment]
The attempt with reaper was my first approach.

Unfortunately the wanted parameters aren't available, so there ist no possibility to map the osc messages.

 

I will see what I can do and wait if there is an answer from the x-audio / myBino team.

 

Thanks a lot for your time an support!

 
 

Gesendet: Mittwoch, 18. Dezember 2019 um 10:53 Uhr
Von: "Alexis Baskind" <notifications@github.com>
An: abaskind/hedrot <hedrot@noreply.github.com>
Cc: halbius <c.alpen@web.de>, Author <author@noreply.github.com>
Betreff: Re: [abaskind/hedrot] Calibrating Accelerometer not possible (#5)


In between I tried the same with pure data (pd extended and vanilla, using sendOSC, as well as packOSC/udpsend): I also don't manage to send messages to mybino. Considering my almost non-existing knowledge of PD, I cannot guarantee that I set everything correctly (although I can send and receive OSC messages within PD), or if the OSC format used in mybino is not 100% compatible with PD. The mybino project being over as well, I guess it may be hard to have tips from the developers.

May I suggest a third solution, using Reaper? The idea is to use the vst version of mybino and instantiate it in audio tracks, then send the OSC messages not to mybino but to reaper itself, then map them in VST parameters. Look at the hedrot manual and/or the video tutorial of mybino for more details.

I'm sorry that I cannot help further for the unstability problems on windows, it's not my speciality at all (I'm a sound engineer, not a software engineer), and since the project is officially over, I don't have enough time to get familiar with it. It would be indeed very good is someone who know the stuff finds the right compilation parameters to make it stable on all versions of Windows 7 and 10. Another very good nice-to-have would be to compile a PD version of hedrot , it's technically possible and probably straightforward for someone who's familiar with compiling PD externals.

Alexis
